const express = require("express");
const router = express.Router();
const { authenticate } = require("../middleware/auth");
const { checkPermission } = require("../middleware/permissions");
const { validate } = require("../middleware/validation");
const Joi = require("joi");
const { sendSuccess, sendError } = require("../ultils/respone");

const thuChiService = require("../services/thuChi.service");

const thuChiSchema = Joi.object({
  // so_phieu is auto-generated by backend
  ngay_giao_dich: Joi.date().required(),
  ma_kho: Joi.string().required(),
  ma_kh: Joi.string().required(),
  so_tien: Joi.number().positive().required(),
  loai: Joi.string().valid("THU", "CHI").required(),
  hinh_thuc: Joi.string()
    .valid("TIEN_MAT", "CHUYEN_KHOAN", "THE")
    .default("TIEN_MAT"),
  dien_giai: Joi.string().allow("", null).optional(),
});

// GET danh sách - KE_TOAN, QUAN_LY, ADMIN
router.get(
  "/",
  authenticate,
  checkPermission("payments", "view"),
  async (req, res, next) => {
    try {
      const data = await thuChiService.getDanhSach(req.query);
      sendSuccess(res, data, "Lấy danh sách thu chi thành công");
    } catch (err) {
      next(err);
    }
  },
);

// GET chi tiết - KE_TOAN, QUAN_LY, ADMIN
router.get(
  "/:so_phieu",
  authenticate,
  checkPermission("payments", "view"),
  async (req, res, next) => {
    try {
      const { so_phieu } = req.params;
      console.log(
        `[ThuChi] GET details for so_phieu: "${so_phieu}" (length: ${so_phieu?.length})`,
      );
      const data = await thuChiService.getChiTiet(so_phieu);
      console.log(
        `[ThuChi] Result for "${so_phieu}":`,
        data ? "FOUND" : "NOT FOUND",
      );
      if (!data) {
        return sendError(res, "Số phiếu không tồn tại", 404);
      }

      return sendSuccess(res, data, "success");
    } catch (error) {
      next(error);
    }
  },
);

// POST tạo phiếu thu chi - KE_TOAN, QUAN_LY, ADMIN
router.post(
  "/",
  authenticate,
  checkPermission("payments", "create"),
  validate(thuChiSchema),
  async (req, res, next) => {
    try {
      const data = {
        ...req.body,
        nguoi_tao: req.user.id,
      };
      const result = await thuChiService.taoPhieu(data);
      sendSuccess(res, result, "Success", 201);
    } catch (error) {
      next(error);
    }
  },
);

// Gửi duyệt - KE_TOAN, QUAN_LY, ADMIN
router.post(
  "/:so_phieu/gui-duyet",
  authenticate,
  checkPermission("payments", "create"),
  async (req, res, next) => {
    try {
      const { so_phieu } = req.params;

      const result = await thuChiService.guiDuyet(so_phieu, req.user.id);

      sendSuccess(res, result, "Success", 201);
    } catch (error) {
      next(error);
    }
  },
);

// Phê duyệt - chỉ QUAN_LY, KE_TOAN, ADMIN
router.post(
  "/:so_phieu/phe-duyet",
  authenticate,
  checkPermission("payments", "approve"),
  async (req, res, next) => {
    try {
      const { so_phieu } = req.params;
      const result = await thuChiService.pheDuyet(so_phieu, req.user.id);
      sendSuccess(res, result, "success", 201);
    } catch (error) {
      next(error);
    }
  },
);
// Hủy phiếu - QUAN_LY, KE_TOAN, ADMIN
router.post(
  "/:so_phieu/huy",
  authenticate,
  checkPermission("payments", "edit"),
  async (req, res, next) => {
    try {
      const { ly_do } = req.body;
      const { so_phieu } = req.params;
      const result = await thuChiService.huyPhieu(so_phieu, req.user.id, ly_do);
      sendSuccess(res, result, "Hủy phiếu thành công");
    } catch (error) {
      next(error);
    }
  },
);
module.exports = router;
