const express = require("express");
const router = express.Router();
const { authenticate } = require("../middleware/auth");
const { checkRole } = require("../middleware/roleCheck");
const { validate } = require("../middleware/validation");
const Joi = require("joi");
const { ROLES } = require("../config/constants");
const { sendSuccess, sendError } = require("../ultils/respone");

const thuChiService = require("../services/thuChi.service");

const thuChiSchema = Joi.object({
  // so_phieu is auto-generated by backend
  ngay_giao_dich: Joi.date().required(),
  ma_kho: Joi.string().required(),
  ma_kh: Joi.string().required(),
  so_tien: Joi.number().positive().required(),
  loai: Joi.string().valid("THU", "CHI").required(),
  dien_giai: Joi.string().allow("", null),
});

router.get("/", authenticate, async (req, res, next) => {
  try {
    const data = await thuChiService.getDanhSach(req.query);
    sendSuccess(res, data, "Lấy danh sách thu chi thành công");
  } catch (err) {
    next(err);
  }
});

router.get("/:so_phieu", authenticate, async (req, res, next) => {
  try {
    const { so_phieu } = req.params;
    console.log(
      `[ThuChi] GET details for so_phieu: "${so_phieu}" (length: ${so_phieu?.length})`
    );
    const data = await thuChiService.getChiTiet(so_phieu);
    console.log(
      `[ThuChi] Result for "${so_phieu}":`,
      data ? "FOUND" : "NOT FOUND"
    );
    if (!data) {
      return sendError(res, "Số phiếu không tồn tại", 404);
    }

    return sendSuccess(res, data, "success");
  } catch (error) {
    next(error);
  }
});

router.post(
  "/",
  authenticate,
  validate(thuChiSchema),
  checkRole(
    ROLES.ADMIN,
    ROLES.NHAN_VIEN,
    ROLES.QUAN_LY_CHI_NHANH,
    ROLES.QUAN_LY_CHI_NHANH
  ),
  async (req, res, next) => {
    try {
      const data = {
        ...req.body,
        nguoi_tao: req.user.username,
      };
      const result = await thuChiService.taoPhieu(data);
      sendSuccess(res, result, "Success", 201);
    } catch (error) {
      next(error);
    }
  }
);

router.post(
  "/:so_phieu/gui-duyet",
  authenticate,
  checkRole(ROLES.ADMIN, ROLES.NHAN_VIEN, ROLES.QUAN_LY_CHI_NHANH),
  async (req, res, next) => {
    try {
      const { so_phieu } = req.params;

      const result = await thuChiService.guiDuyet(so_phieu, req.user.username);

      sendSuccess(res, result, "Success", 201);
    } catch (error) {
      next(error);
    }
  }
);

router.post(
  "/:so_phieu/phe-duyet",
  authenticate,
  checkRole(ROLES.ADMIN, ROLES.QUAN_LY_CHI_NHANH, ROLES.QUAN_LY_CTY),
  async (req, res, next) => {
    try {
      const { so_phieu } = req.params;
      const result = await thuChiService.pheDuyet(so_phieu, req.user.username);
      sendSuccess(res, result, "success", 201);
    } catch (error) {
      next(error);
    }
  }
);
router.post(
  "/:so_phieu/huy",
  authenticate,
  checkRole(ROLES.ADMIN, ROLES.QUAN_LY_CHI_NHANH, ROLES.QUAN_LY_CTY),
  async (req, res, next) => {
    try {
      const { ly_do } = req.body;
      const { so_phieu } = req.params;
      const result = await thuChiService.huyPhieu(
        so_phieu,
        req.user.username,
        ly_do
      );
      sendSuccess(res, result, "Hủy phiếu thành công");
    } catch (error) {
      next(error);
    }
  }
);
module.exports = router;
