apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: motor-manage
type: Opaque
stringData:
  DB_PASSWORD: "password"
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/Manage_Warehouse"
  JWT_SECRET: "your_super_secret_key"
  JWT_REFRESH_SECRET: "your_refresh_secret_key"
  VAPID_PUBLIC_KEY: "BLuAqyGbIUufdOH9w6ODOzMDYmXHbmLH6UWzNbUU5SZ73yh1StnNLZiFgyPZyAkAUFWbqEWScqdW5Sbhs_x4DYo"
  VAPID_PRIVATE_KEY: "JXEkx-hbNS-kXywsC6nufytdoDAluhhxGgydhatAVLg"
