apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: motor-manage
spec:
  selector:
    app: motor-manage-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
